Starting job at Thu Feb 13 05:02:17 PM CET 2025
Running Filter_by_part.py for subdirectory 22010, part 10
2025-02-13 17:02:18 - INFO - Event filtering process starts...
2025-02-13 17:02:18 - INFO - Initialized Muon13Filter
2025-02-13 17:02:18 - INFO - Starting filtering process for 22010/10
2025-02-13 17:02:47 - INFO - Recalculated 'offset' column based on filtered 'N_doms' values.
2025-02-13 17:02:51 - INFO - Filtered truth file saved to: /lustre/hpc/project/icecube/HE_Nu_Aske_Oct2024/PMTfied_filtered/MuonLike/Snowstorm/22010/truth_10.parquet
2025-02-13 17:02:52 - INFO - Receipt file saved to: /lustre/hpc/project/icecube/HE_Nu_Aske_Oct2024/PMTfied_filtered/MuonLike/Snowstorm/22010/[Receipt]22010_10.json
2025-02-13 17:02:52 - ERROR - An error occurred: 'Field "event_no" does not exist in schema'
Traceback (most recent call last):
  File "/lustre/hpc/icecube/cyan/factory/DOMification/Selection/Filter_by_part.py", line 85, in <module>
    main()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/Selection/Filter_by_part.py", line 81, in main
    run()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/Selection/Filter_by_part.py", line 72, in run
    event_filter()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/Selection/Muon13Filter.py", line 22, in __call__
    self._filter_shards()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/Selection/EventFilter.py", line 62, in _filter_shards
    pmt_event_nos = pmt_table.column("event_no").to_pylist()
  File "pyarrow/table.pxi", line 1779, in pyarrow.lib._Tabular.column
  File "pyarrow/table.pxi", line 1715, in pyarrow.lib._Tabular._ensure_integer_index
KeyError: 'Field "event_no" does not exist in schema'
Job completed at Thu Feb 13 05:02:52 PM CET 2025
